/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ContextoRouteImport } from './routes/contexto'
import { Route as CheckpointsRouteImport } from './routes/checkpoints'
import { Route as AgoraRouteImport } from './routes/agora'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IlhasIslandIdRouteImport } from './routes/ilhas.$islandId'

const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextoRoute = ContextoRouteImport.update({
  id: '/contexto',
  path: '/contexto',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckpointsRoute = CheckpointsRouteImport.update({
  id: '/checkpoints',
  path: '/checkpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const AgoraRoute = AgoraRouteImport.update({
  id: '/agora',
  path: '/agora',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IlhasIslandIdRoute = IlhasIslandIdRouteImport.update({
  id: '/ilhas/$islandId',
  path: '/ilhas/$islandId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agora': typeof AgoraRoute
  '/checkpoints': typeof CheckpointsRoute
  '/contexto': typeof ContextoRoute
  '/perfil': typeof PerfilRoute
  '/projetos': typeof ProjetosRoute
  '/sistema': typeof SistemaRoute
  '/ilhas/$islandId': typeof IlhasIslandIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agora': typeof AgoraRoute
  '/checkpoints': typeof CheckpointsRoute
  '/contexto': typeof ContextoRoute
  '/perfil': typeof PerfilRoute
  '/projetos': typeof ProjetosRoute
  '/sistema': typeof SistemaRoute
  '/ilhas/$islandId': typeof IlhasIslandIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agora': typeof AgoraRoute
  '/checkpoints': typeof CheckpointsRoute
  '/contexto': typeof ContextoRoute
  '/perfil': typeof PerfilRoute
  '/projetos': typeof ProjetosRoute
  '/sistema': typeof SistemaRoute
  '/ilhas/$islandId': typeof IlhasIslandIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/agora'
    | '/checkpoints'
    | '/contexto'
    | '/perfil'
    | '/projetos'
    | '/sistema'
    | '/ilhas/$islandId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/agora'
    | '/checkpoints'
    | '/contexto'
    | '/perfil'
    | '/projetos'
    | '/sistema'
    | '/ilhas/$islandId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/agora'
    | '/checkpoints'
    | '/contexto'
    | '/perfil'
    | '/projetos'
    | '/sistema'
    | '/ilhas/$islandId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AgoraRoute: typeof AgoraRoute
  CheckpointsRoute: typeof CheckpointsRoute
  ContextoRoute: typeof ContextoRoute
  PerfilRoute: typeof PerfilRoute
  ProjetosRoute: typeof ProjetosRoute
  SistemaRoute: typeof SistemaRoute
  IlhasIslandIdRoute: typeof IlhasIslandIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexto': {
      id: '/contexto'
      path: '/contexto'
      fullPath: '/contexto'
      preLoaderRoute: typeof ContextoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkpoints': {
      id: '/checkpoints'
      path: '/checkpoints'
      fullPath: '/checkpoints'
      preLoaderRoute: typeof CheckpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agora': {
      id: '/agora'
      path: '/agora'
      fullPath: '/agora'
      preLoaderRoute: typeof AgoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilhas/$islandId': {
      id: '/ilhas/$islandId'
      path: '/ilhas/$islandId'
      fullPath: '/ilhas/$islandId'
      preLoaderRoute: typeof IlhasIslandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AgoraRoute: AgoraRoute,
  CheckpointsRoute: CheckpointsRoute,
  ContextoRoute: ContextoRoute,
  PerfilRoute: PerfilRoute,
  ProjetosRoute: ProjetosRoute,
  SistemaRoute: SistemaRoute,
  IlhasIslandIdRoute: IlhasIslandIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
